# Generated by Django 4.0.5 on 2022-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='room_image',
            field=models.ImageField(blank=True, upload_to='rooms/'),
        ),
    ]
